services:
  codeserver:
    image: gitlab/gitlab-ee:16.11.2-ee.0
    container_name: stokejo
    restart: always
    volumes:
      - /stokejo/opt:/var/opt/gitlab
      - /stokejo/kkk:${KEY_PATH}
      - /stokejo/inf:/var/log/gitlab
      - /stokejo/etc:/etc/gitlab
    ports:
      - "127.0.0.1:5050:5050"
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:2020:22"
