services:
  runnerserver:
    image: gitlab/gitlab-runner:latest
    container_name: stokejo-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /stokejo/run/stokejo:/etc/gitlab-runner
