services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    volumes:
      - /stokejo/jellyfin/etc:/jellyfin/etc
      - /stokejo/jellyfin/var:/jellyfin/var
      - /stokejo/jellyfin/tmp:/jellyfin/tmp
      - /stokejo/jellyfin/log:/jellyfin/log
      - /stokejo/jellyfin/dat:/jellyfin/dat
    environment:
      https_proxy: "http://10.44.44.10:8118"
      http_proxy: "http://10.44.44.10:8118"
      JELLYFIN_CONFIG_DIR: "/jellyfin/etc"
      JELLYFIN_DATA_DIR: "/jellyfin/var"
      JELLYFIN_CACHE_DIR: "/jellyfin/tmp"
      JELLYFIN_LOG_DIR: "/jellyfin/log"
    ports:
      - "127.0.0.1:8096:8096"
